version: '3.8'
services:
  # PostgreSQL service
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '0.0.0.0:5432:5432'

  # Backend Api service
#   api:
#     build: .
#     ports:
#       - '8081:8080'
#     volumes:
#       - .:/usr/src/app
#       - /usr/src/app/node_modules
#     command: npm run start:docker
#     environment:
#       PORT: 8080
#     restart: always
#     depends_on:
#       - db

# networks:
#   common_network:
