-- INSERT INTO lesson (name, contents, category_id)
-- VALUES (
--         'Advanced SQL',
--         'Discuss advanced SQL techniques, including subqueries, joins, and views.',
--         (
--             SELECT category_id
--             FROM lesson_category
--             WHERE name = 'Computer Science'
--         )
--     ),
--     (
--         'Data Visualization',
--         'Learn how to create visually appealing data visualizations using tools like Tableau or Power BI.',
--         (
--             SELECT category_id
--             FROM lesson_category
--             WHERE name = 'Computer Science'
--         )
--     ),
--     (
--         'Web Development',
--         'Learn how to build interactive websites using HTML, CSS, and JavaScript.',
--         (
--             SELECT category_id
--             FROM lesson_category
--             WHERE name = 'Computer Science'
--         )
--     ),
--     (
--         'Machine Learning',
--         'Discuss machine learning algorithms, techniques, and applications.',
--         (
--             SELECT category_id
--             FROM lesson_category
--             WHERE name = 'Computer Science'
--         )
--     )